name: Minikube Setup

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Start minikube
        uses: medyagh/setup-minikube@latest
        
      - name: Ensure kubectl is working
        run: |
          kubectl version --client
          kubectl get pods -A
          kubectl cluster-info --context minikube
